version: '3'
services:
  app:
    build: .
    command: uvicorn app:app --host 0.0.0.0 --port 5000 --reload 
    #python -u app.py 
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - db
    depends_on:
      - db
  db:
    image: mongo:latest
    hostname: test_mongodb
    environment:
      - MONGO_INITDB_DATABASE=pokedex_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    ports:
      - 27017:27017
